### ISSUE TITLE
Weird behavior if button clicked while transition in progress

### ISSUE THREAD

**Issue by linusmarco** [ignacio82/vizdraws#17]
If you click the button while the visualization is transitioning from distribution -> bars, you end up with the following:

![image](https://user-images.githubusercontent.com/18667084/33440268-90329b70-d5bd-11e7-903e-9d5a0d652784.png)

I think we should fix this by disabling/hiding the button during the transitions. There's no good reason for the user to switch while a transition is in progress.

**Comment by ignacio82** [comment]
Sounds like a good solution. Thanks!
