### ISSUE TITLE
Odd behavior if MME is less than 0

### ISSUE THREAD

**Issue by linusmarco** [ignacio82/vizdraws#18]
If MME is less than zero we end up with overlapping distribution sections and other weird/unexpected behavior. Of course MME should be strictly non-negative, so I think we have 2 options here:
1. Handle this by throwing an error in the R code before the app is even launched
2. In the JS code, just take the absolute value of negative MMEs

@ignacio82 -- this came up briefly on an earlier PR but we never resolved it. Do you have a preference between the options above? I lean towards option 1. I think 2 may be confusing for the user

**Comment by ignacio82** [comment]
I think adding one line of R code is the best option:

     if(MME<0) stop("MME should be non-negative")

I can do that later today.
