### ISSUE TITLE
resize method does not work

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#19]
We need to figure out how to make the resize method work. I looked at [the documentation](http://www.htmlwidgets.org/develop_sizing.html) and tried a few different things that did not work. @timelyportfolio could you point us in the right direction?

**Comment by linusmarco** [comment]
The reason the resize method doesn't work as-is is that right now it just appends a new <svg> to the container element without modifying anything about the original graphic. I think the easiest thing to do will be to just have the resize method completely redraw the viz without doing the initial animation. We could also use the new width and height to individually resize each piece of the viz, but that may be a bit complex--I'll have to think about it

**Comment by timelyportfolio** [comment]
`resize` can range from easy to complex.  The choice depends on your desire to animate the transition from one size to the next, and often this relates to whether or not you are animating the `render` when you get new data.  Currently, this widget wipes out current on render, so for now I would think `resize` would pursue the same approach.  If you choose this easier route, you can just do 

```
renderValue: function(opts) {
...
  this.opts = opts
},
resize: function(width, height) {
  // need x for renderValue which requires storing x (or opts) in renderValue
  //  on this binding; see the change above in renderValue when opts in scope
  this.renderValue(this.opts)
}
```

I hope this helps.  I usually like to create a `draw` function that handles the update, but it is not necessary.

**Comment by timelyportfolio** [comment]
Also, I tend to see confusion as to why `resize` might not be called.  The default size of an `htmlwidget` is fixed, so resizing the window will not trigger `resize`.  Providing a `width = "100%"` is the most straightforward way to get resize.

**Comment by ignacio82** [comment]
@drcthal any chance that you can take a look at this? 

https://github.com/ignacio82/IMPosterior/blob/b266acf424f832d375bd20a4c209f83585494031/inst/htmlwidgets/IMPosterior.js#L590
