### ISSUE TITLE
Plot does not render if you call IMPosterior more than once

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#23]
```r
library(shiny)

  
  ui <- fluidPage(
    
    sidebarLayout(
      sidebarPanel(
        p('The modal graph will not populate when run 2+ times. The static plot is fine (needs to be uncommented)'),
        actionButton('run', 'Run')
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
        IMPosterior::IMPosteriorOutput("staticplot")
      )
    )
  )
  
  server <- function(input, output, session) {
    
    im_object <- eventReactive(input$run,{
      IMPosterior::IMPosterior(sample(-500:500,50,replace = T), MME = 10, threshold = .7)
    })
    
    # output$staticplot <- IMPosterior::renderIMPosterior({
    #   im_object()
    # })
    
    output$modalplot <- IMPosterior::renderIMPosterior({
      im_object()
    })
    
    observeEvent(input$run,{
      req(im_object())
      showModal(modalDialog(
        IMPosterior::IMPosteriorOutput('modalplot'),
        title = 'Modal Plot',
        easyClose = T,
        size = 'm'
      ))
    })
    
  }
  
  # Run the application 
  shinyApp(ui = ui, server = server)
```

This is what the console shows:

```js
IMPosterior.js:454 Uncaught ReferenceError: dims is not defined
    at Object.resize (IMPosterior.js:454)
    at Object.resize (htmlwidgets.js:825)
    at exports.OutputBinding.shinyBinding.resize (htmlwidgets.js:526)
    at output_binding_adapter.js:12
    at OutputBindingAdapter.onResize (utils.js:114)
    at HTMLDivElement.<anonymous> (init_shiny.js:309)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at j (init_shiny.js:302)
    at Debouncer.$invoke (input_rate.js:56)
```

![Apr 23 2019 9_02 AM - Edited](https://user-images.githubusercontent.com/1833309/56583489-abeeab80-65a7-11e9-8e3c-68f1659a7256.gif)

@timelyportfolio any chance that you can point me in the right direction on what could be causing this bug and how to fix it?

**Comment by stephanietuerk** [comment]
- It appears that when the plot is created a second time, htmlwidgets calls render(), resize(), and render(). This seems like strange behavior -- seems like it should either call resize() or render() but not both and certainly not render() twice.  
- When render() is called these two times, the width, height values passed in are 0, 0. When render() is called the first time, the value is as specified in R. (568, 500)

**Comment by ignacio82** [comment]
Thanks @stephanietuerk  . I'm wondering if this could be a bug in htmlwidgets. I will ask.

PS: Here is a video that shows the problem in case someone else is curious

![Apr 25 2019 3_45 PM - Edited](https://user-images.githubusercontent.com/1833309/56764014-b9f02800-6771-11e9-84c0-f7667dc4dd50.gif)
