### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#27]
Ideas: 
* vizdraws
* drawsviz
* viz4draws

**Comment by ignacio82** [comment]
@drcthal any preference? do you particularly like or dislike one of these? do you have some other idea?

**Comment by drcthal** [comment]
Those are fine. I'd say better to not have a number in it, so maybe 1st or 2nd? Could also stick posterior or post in there (vizpostdraws, postdrawsviz), but that's getting a bit clunky.

**Comment by ignacio82** [comment]
The winner of [our very popular staw poll](https://www.strawpoll.me/18239577/r) is `vizdraws`. I will close this issue once I make the changes.
