### ISSUE TITLE
add argument for "breaks"

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#41]
@drcthal how hard would it be to add an additional argument to the function so we can pass `breaks = c(-1,0,5)` and the density is splited into 3 areas. This argument would be an alternative to `MME`. when this argument is used instead of MME the tooltip text would change to something like `X% probability that [units] is less than -1; Y% [units] is between -1 and 0`; Z% that [units] is >5` . A few more details

* breaks should take a vector of any length
* when breaks is passed as an argument MME should not be passed and units should be

**Comment by drcthal** [comment]
Ok, you can check out my branch mutliple-breaks for a first cut. Takes the argument breaks and break_names (what shows up on the bar chart). I have default names & color schemes up to 10 breaks/11 groups, but they are bad.
I tried to make the text stay general, so it's always "Your[data suggest/priors imply] that there is a x% probability that the intervention has an effect [less than y/between y and z/of more than y][units]." regardless of MME vs. breaks. 

`prior <- rnorm(1000, mean=0, sd = 1)`
`IMPosterior(prior=prior, MME=0)`
`IMPosterior(prior=prior, MME=1)`
`IMPosterior(prior=prior, breaks=c(-2,-1,1,2))`
`IMPosterior(prior=prior, breaks=c(-2,-1.5,-1,-0.5,0.5,1,1.5,2))`

**Comment by ignacio82** [comment]
Thanks @drcthal ! This is great.

One problem with the text as we have it is that the use case that I have in mind for when you provide multiple breaks is not an intervention. For example, what I want to do is predict the number of applications to a school and the breaks would be something like fewer than 10 applications between 11 and 20, more than 20.

I'm not sure what is the best way of implementing this.

**Comment by ignacio82** [comment]
Maybe the solution is to have 2 R functions instead of the single `IMPosterior` One would be something like `draws_intervention` and the other `draws_prediction` and the only real difference is the text we use. Thoughts?

**Comment by drcthal** [comment]
Separate function would definitely work. We could also just make it always vague like your original idea above ("your data suggest x% probability between y and z"). More sophisticated, maybe we could do something like have the text components be arguments. e.g. feed R the arguments
`prior_prefix = 'Your priors suggest'`
`posterior_prefix = 'Your data suggest'`
`main_text = 'that there is a ^^^prob% probability that the intervention has an effect'`
`lb_suffix = 'less than ^^^lb ^^^units'`
`mid_suffix = 'between ^^^lb and ^^^ub ^^^units'`
`ub_suffix = 'of more than ^^^ub ^^^units'`
and the js just fills in the ^^^placeholders and binds them together.
So to get it the way it works now you'd feed in the above. To get what you want, you'd change the `main_text` argument to `'that there is ^^^prob% chance that enrollment is'`
And to get the vague version you just change `main_text` to `'^^^prob% probability'`.

**Comment by ignacio82** [comment]
I think out of all these the best solution is to have two functions, one for visualizing draws for an impact and one for draws for a predicted quantity like school enrollment, or expenditure. This will allow us to be opinionated with the text and protect users from writing things that are wrong while it will also be simpler to use. Do you agree?

**Comment by drcthal** [comment]
Good point, I didn't think about that protection from misuse. What about just an option for quantity vs. impact? (like argument `quantity`, defaults to false)? I don't love the idea of having to maintain a nearly-identical copy of the function.

**Comment by ignacio82** [comment]
That is a good idea. Adding an argument will allow us to have differentiated text and keep things simple at the same time.

**Comment by drcthal** [comment]
Ok, pushed that. Grammar is gonna be a little funny, e.g. probability that "students are between 1 and 2" vs "number of students is between 1 and 2" vs. "enrollment will be between 20 and 30" so maybe the units option should be allowed to encompass the is/are/will be piece as well?

`IMPosterior(prior=prior, breaks=c(-2,-1,1,2))`
`IMPosterior(prior=prior, breaks=c(-2,-1,1,2), quantity=TRUE, units = 'students')`

**Comment by ignacio82** [comment]
This looks great, but I think given that the intended use is predictions we want to use `will be`. That is:

```Your prior implies that there is a [x%] probability that [units] will be between [a] and [b]```
