### ISSUE TITLE
It crashes when MME is to the left of the min value of x

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#8]
# Gen data --------------------------------------------------------------
    set.seed(9782)
    x <- rnorm(n = 1000, mean = 5, sd = 1)
    
    
    # Usy my widget -----------------------------------------------------------
    library(IMPosterior)
    IMPosterior(x= x, MME=0)

**Comment by linusmarco** [comment]
PR #10 addresses this
